apiVersion: v1
kind: Pod
metadata:
  name: sc-pod
spec:
  containers:
    - name: writer
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            echo "Written via StorageClass: $(date)" >> /data/out.txt;
            sleep 10;
          done
      volumeMounts:
        - name: sc-storage
          mountPath: /data

  volumes:
    - name: sc-storage
      persistentVolumeClaim:
        claimName: test2-svc