apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: role-database
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["postgres-secret"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["postgres-init"]
  verbs: ["get"]