apiVersion: v1
kind: Pod
metadata:
  name: burstable-test
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        requests:
          memory: 300Mi
          cpu: 200m
        limits:
          memory: 600Mi
          cpu: 500m
      ports:
        - containerPort: 80

    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          memory: "100Mi"
          cpu: "50m"
        limits:
          memory: "200Mi"
          cpu: "150m"