apiVersion: v1
kind: Pod
metadata:
  name: oom-killer
spec:
  containers:
    - name: stress
      image: polinux/stress
      resources:
        requests:
          memory: "100Mi"
        limits:
          memory: "200Mi"
      command: ["sh", "-c"]
      args:
        - |
          while true; do
            stress --vm 1 --vm-bytes 5M --vm-hang 0 --timeout 60s
            sleep 1;
          done