apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: stress
      image: polinux/stress
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "200m"
          memory: "200Mi"
      command: ["sleep", "3600"]