apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: stress
      image: polinux/stress
      resources:
        requests:
          cpu: "300m"
          memory: "300Mi"
        limits:
          cpu: "500m"
          memory: "500Mi"
      command: ["sleep", "3600"]