apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-api
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: sa-frontend    
      containers:
        - name: frontend-api
          image: flask-frontend:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          env:
            - name: BACKEND_URL
              value: "http://backend-api:80"